# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: seanhsieh
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-lambda-node-express
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-node-express

resources:
  Resources:
    userDemo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userDemo
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [userDemo, Arn]

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
